name: Go

on:
  push:
    branches: [ main ]
    tags: ['v*']
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.17.*", "1.18.*", "1.19.*"]
        include:
          - go: 1.19.*
            latest: true

    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Load cached dependencies
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Test
        run: make cover

      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v1
